###################
# Lock Automations
###################

    
- id: 'lock_after_10pm_back_door'
  alias: 'Lock Back Door at 10pm'
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock
    
- id: 'lock_after_midnight_back_door'
  alias: 'Lock Back Door at midnight'
  trigger:
    platform: time
    at: '00:01:00'
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock

- id: 'lock_after_10_mins_when_after_10pm_or_before_4pm_back_door'
  alias: 'Weekday Lock Schedule back door'
  trigger:
    platform: state
    entity_id: lock.lock_back_door_lock
    to: 'unlocked'
    for:
      minutes: 10
  condition:
    condition: time
    after: '22:00:00'
    before: '16:30:00'
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock
    

- id: 'lock_after_10_mins_when_between_midnight_11am_back_door'
  alias: 'Sunday Lock Schedule back door'
  trigger:
    platform: state
    entity_id: lock.lock_back_door_lock
    to: 'unlocked'
    for:
      minutes: 10
  condition:
    condition: time
    after: '00:00:00'
    before: '11:00:00'
    weekday:
        - sun
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock

    
- id: 'lock_after_10pm_front_door'
  alias: 'Lock Front Door at 10pm'
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock    
    
- id: 'lock_after_midnight_front_door'
  alias: 'Lock Front Door at midnight'
  trigger:
    platform: time
    at: '00:01:00'
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock        

    
- id: 'lock_after_10_mins_when_after_10pm_or_before_4pm_front_door'
  alias: 'Weekday Lock Schedule front door'
  trigger:
    platform: state
    entity_id: lock.lock_front_door_lock
    to: 'unlocked'
    for:
      minutes: 10
  condition:
    condition: time
    after: '22:00:00'
    before: '16:30:00'
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock
    
- id: 'lock_after_10_mins_when_between_midnight_11am_front_door'
  alias: 'Sunday Lock Schedule front door'
  trigger:
    platform: state
    entity_id: lock.lock_front_door_lock
    to: 'unlocked'
    for:
      minutes: 10
  condition:
    condition: time
    after: '00:00:00'
    before: '11:00:00'
    weekday:
        - sun
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock
    


