###################
# Lock Automations
###################

    
- id: 'lock_after_10pm_back_door'
  alias: 'Lock Back Door at 10pm'
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock
    
- id: 'lock_after_midnight_back_door'
  alias: 'Lock Back Door at midnight'
  trigger:
    platform: time
    at: '00:01:00'
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock

- id: 'lock_after_5_mins_back_door'
  alias: 'Lock Schedule Back Door'
  trigger:
    platform: state
    entity_id: lock.lock_back_door_lock
    to: 'unlocked'
    for:
      minutes: 5
  condition:
    condition: time
    after: '00:01:00'
    before: '23:59:59'
    weekday:
        - mon
        - tue
        - wed
        - fri
        - sat
        - sun
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock
    

- id: 'lock_after_5_mins_before_6pm_after_11pm_back_door'
  alias: 'HomeChurch Lock Schedule back door'
  trigger:
    platform: state
    entity_id: lock.lock_back_door_lock
    to: 'unlocked'
    for:
      minutes: 5
  condition:
    condition: time
    after: '23:00:00'
    before: '17:00:00'
    weekday:
        - thu
  action:
    service: lock.lock
    entity_id: lock.lock_back_door_lock

    
- id: 'lock_after_10pm_front_door'
  alias: 'Lock Front Door at 10pm'
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock    
    
- id: 'lock_after_midnight_front_door'
  alias: 'Lock Front Door at midnight'
  trigger:
    platform: time
    at: '00:01:00'
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock        

    
- id: 'lock_after_5_mins_front_door'
  alias: 'Lock Schedule front door'
  trigger:
    platform: state
    entity_id: lock.lock_front_door_lock
    to: 'unlocked'
    for:
      minutes: 5
  condition:
    condition: time
    after: '00:01:00'
    before: '23:59:59'
    weekday:
        - mon
        - tue
        - wed
        - fri
        - sat
        - sun
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock
    
- id: 'lock_after_5_mins_before_6pm_after_11pm_front_door'
  alias: 'HomeChurch Lock Schedule front door'
  trigger:
    platform: state
    entity_id: lock.lock_front_door_lock
    to: 'unlocked'
    for:
      minutes: 5
  condition:
    condition: time
    after: '23:00:00'
    before: '17:00:00'
    weekday:
        - thu
  action:
    service: lock.lock
    entity_id: lock.lock_front_door_lock
    