homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret myLatitude
  longitude: !secret myLongitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 901
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: EST
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#Panels
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
    
#Devices Added
ecobee:
    api_key: !secret ecobeeAPIKey

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0xF3, 0x5F, 0x31, 0xB4, 0xA6, 0x22, 0xB8, 0x3F, 0x25, 0x33, 0xCF, 0xE6, 0x89, 0x12, 0x42, 0x76"
  
octoprint:
  host: 192.168.7.151
  api_key: !secret octopringAPIKey
  bed: true
  number_of_tools: 1
  
camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octoprint_still_image_url
    mjpeg_url: !secret octoprint_mjpeg_url

# Cloud
cloud:

script: !include scripts.yaml
automation: !include automations.yaml
group: !include groups.yaml